package com.evento.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AsientoSeleccionadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoSeleccionadoAllPropertiesEquals(AsientoSeleccionado expected, AsientoSeleccionado actual) {
        assertAsientoSeleccionadoAutoGeneratedPropertiesEquals(expected, actual);
        assertAsientoSeleccionadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoSeleccionadoAllUpdatablePropertiesEquals(AsientoSeleccionado expected, AsientoSeleccionado actual) {
        assertAsientoSeleccionadoUpdatableFieldsEquals(expected, actual);
        assertAsientoSeleccionadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoSeleccionadoAutoGeneratedPropertiesEquals(AsientoSeleccionado expected, AsientoSeleccionado actual) {
        assertThat(actual)
            .as("Verify AsientoSeleccionado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoSeleccionadoUpdatableFieldsEquals(AsientoSeleccionado expected, AsientoSeleccionado actual) {
        assertThat(actual)
            .as("Verify AsientoSeleccionado relevant properties")
            .satisfies(a -> assertThat(a.getFila()).as("check fila").isEqualTo(expected.getFila()))
            .satisfies(a -> assertThat(a.getColumna()).as("check columna").isEqualTo(expected.getColumna()))
            .satisfies(a -> assertThat(a.getNombrePersona()).as("check nombrePersona").isEqualTo(expected.getNombrePersona()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoSeleccionadoUpdatableRelationshipsEquals(AsientoSeleccionado expected, AsientoSeleccionado actual) {
        assertThat(actual)
            .as("Verify AsientoSeleccionado relationships")
            .satisfies(a -> assertThat(a.getSesion()).as("check sesion").isEqualTo(expected.getSesion()));
    }
}
